[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]


[build]
target = "x86_64-Ducu_os.json"

[target.'cfg(target_os="none")']
runner="D:\\qemu\\qemu-system-x86_64.exe -drive format=raw,file="